#!/bin/bash

TEXT_BOLD=$(tput bold)
TEXT_BLUE=$(tput setaf 4)
TEXT_NORMAL=$(tput sgr0)

puts()  { printf "%s\n" "${1}" ; }
puts-blue() { printf "%s\n" "${TEXT_BOLD}${TEXT_BLUE}${1}${TEXT_NORMAL}" ; }
log-info() { >&2 puts-blue "$(basename "$0") ${1}" ; }
log-err() { >&2 puts-red "$(log_get_title)${1}" ; }

url="$1"
if [[ -z "$url" ]]; then
  puts "Usage: $(basename "$0") <url>"
  exit 1
fi

filename=$(basename "$url")
filepath="$HOME"/Downloads/"$filename"

# destination directory must exist
if [[ ! -d "$HOME"/Downloads ]]; then
  log-err "Directory does not exist \"$HOME/Downloads\"."
  exit 1 
fi

# download file
if [[ ! -f "$filepath" ]]; then
  log-info "Downloading \"$url\" to \"$HOME/Downloads\"..."
  if ! curl -sfL -o "$filepath" "$url"; then
    log-err "Failed to download \"$url\"."
    exit 1
  fi
fi

# print path of downloaded file
puts "$filepath"
