#!/bin/bash

set -euo pipefail

default_path=$HOME/Downloads

usage() {
  cat <<EOF
Usage: $0 <URL>

Downloads <URL> to $default_path
EOF
}

err()   { 2>&1 printf "%s%s%s\n" "$(tput setaf 1)" "$@" "$(tput sgr0)"; }
warn()  { 2>&1 printf "%s%s%s\n" "$(tput setaf 3)" "$@" "$(tput sgr0)"; }
info()  { 2>&1 printf "%s%s%s\n" "$(tput setaf 4)" "$@" "$(tput sgr0)"; }
onerr() { local s=$?; err "$0:${BASH_LINENO[0]} $BASH_COMMAND"; exit $s; }

main() {
  trap onerr ERR
  path="$default_path"

  while getopts 'h' flag; do
    case "${flag}" in
      *) usage ; exit 1 ;; 
    esac
  done

  url="${1:-}"
  if [[ -z "$url" ]]; then
    usage
    exit 1
  fi

  filename=$(basename "$url")
  filepath=$path/$filename

  if [[ ! -f "$filepath" ]]; then
    info "Downloading \"$url\" to \"$filepath\"..."
    mkdir -p "$path"
    curl -sfL -o "$filepath" "$url"
  fi

  # print path of downloaded file
  printf "%s\n" "$filepath"
}

main "$@"
