#!/bin/bash

has_nomodeset() {
  r=$(sudo cat /sys/module/nvidia_drm/parameters/modeset)
  [[ "$r" == "Y" ]] && return 0 || return 1
}

if ! has_nomodeset; then
  echo "nvidia-drm modeset is *not* enabled"
  mpconf=/etc/modprobe.d/nvidia-drm-nomodeset.conf
  if [[ ! -f $mpconf ]]; then
    2>&1 echo "Creating $mpconf"
    echo "options nvidia-drm modeset=1" | sudo tee $mpconf
    2>&1 echo "Calling update-initramfs"
    sudo update-initramfs -u
    2>&1 echo "*** REBOOT REQUIRED ***"
  fi

  echo "enable PRIME synchronization"
  xrandr --output eDP-1-1 --set "PRIME Synchronization" 1
else
  echo "nvidia-drm nomodeset *is* enabled. Good."
fi

